/home/haseeb/crypto_prices_project/crypto_prices_project/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/haseeb/crypto_prices_project/crypto_prices_project/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/haseeb/crypto_prices_project/crypto_prices/views.py changed, reloading.
Watching for file changes with StatReloader
/home/haseeb/crypto_prices_project/crypto_prices/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/models/query.py", line 948, in get_or_create
    return self.get(**kwargs), False
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/models/query.py", line 649, in get
    raise self.model.DoesNotExist(
crypto_prices.models.Currency.DoesNotExist: Currency matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: crypto_prices_currency.crypto_prices_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/haseeb/crypto_prices_project/crypto_prices/views.py", line 28, in display_prices
    static_data = generate_static_data()
  File "/home/haseeb/crypto_prices_project/crypto_prices/views.py", line 15, in generate_static_data
    currency, created = Currency.objects.update_or_create(
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/models/query.py", line 986, in update_or_create
    obj, created = self.select_for_update().get_or_create(
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/models/query.py", line 955, in get_or_create
    return self.create(**params), True
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/models/base.py", line 1067, in _save_table
    results = self._do_insert(
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/models/base.py", line 1108, in _do_insert
    return manager._insert(
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: crypto_prices_currency.crypto_prices_id
/home/haseeb/crypto_prices_project/crypto_prices/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/haseeb/crypto_prices_project/crypto_prices/views.py", line 31, in display_prices
    return render(request, 'prices.html', {'currencies': currencies})
NameError: name 'render' is not defined
Internal Server Error: /
Traceback (most recent call last):
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/haseeb/crypto_prices_project/crypto_prices/views.py", line 31, in display_prices
    return render(request, 'prices.html', {'currencies': currencies})
NameError: name 'render' is not defined
/home/haseeb/crypto_prices_project/crypto_prices/views.py changed, reloading.
Watching for file changes with StatReloader
/home/haseeb/crypto_prices_project/crypto_prices/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/haseeb/crypto_prices_project/crypto_prices/views.py", line 31, in display_prices
    latest_timestamp=Max('crypto_prices__timestamp'))['latest_timestamp']
NameError: name 'Max' is not defined
/home/haseeb/crypto_prices_project/crypto_prices/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/haseeb/crypto_prices_project/crypto_prices/views.py", line 30, in display_prices
    latest_timestamp = Currency.objects.aggregate(
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/models/query.py", line 591, in aggregate
    self._validate_values_are_expressions(
  File "/home/haseeb/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1997, in _validate_values_are_expressions
    raise TypeError(
TypeError: QuerySet.aggregate() received non-expression(s): y.
/home/haseeb/crypto_prices_project/crypto_prices/views.py changed, reloading.
Watching for file changes with StatReloader
/home/haseeb/crypto_prices_project/crypto_prices/views.py changed, reloading.
Watching for file changes with StatReloader
